name: Bug
description: Fix a defect
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: repro
    attributes:
      label: Repro
      description: Steps to reproduce
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [P0, P1, P2]
